controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


Home:
    path: /
    controller: App\Controller\HomeController::index

HomeAdmin:
    path: /Admin
    controller: App\Controller\Admin\AdminHomeController::index

AddProf:
    path: /Admin/addProfesseur
    conroller: App\Controller\Admin\ProfesseurController::new
 